### ISSUE TITLE
Create color palette

### ISSUE THREAD

**Issue by bajabob** [bajabob/Patient-Itinerary-Planner#2]
Need a color palette to use for future designing. Should include Hex color codes.

**Comment by bajabob** [comment]
Matt's progress:

<img width="946" alt="color scheme" src="https://cloud.githubusercontent.com/assets/273841/12967348/a1ad83b8-d02b-11e5-9aa4-8353fddbefb1.png">

**Comment by baileybauman** [comment]
finished
