### ISSUE TITLE
UI wireframes

### ISSUE THREAD

**Issue by bajabob** [bajabob/Patient-Itinerary-Planner#3]
Need a series of wireframes of all screens. These should be hand drawn and uploaded.

Wireframes should show some idea of what the screen does and what screens it links too like a flow diagram. 

Create lo-fi UI mockups and storyboards for at least 4 user stories. Submit photos of these.

NOTE: These wireframes should also include the ones completed in User Stories #8

**Comment by mdyl** [comment]
Version 1 of the UI design/mockup have been completed.
[UI Design Version 1.zip](https://github.com/bajabob/Patient-Itinerary-Planner/files/129885/UI.Design.Version.1.zip)
