### ISSUE TITLE
Edit client interview, upload to YouTube

### ISSUE THREAD

**Issue by bajabob** [bajabob/Patient-Itinerary-Planner#6]
Take videos created in #5 and edit together. Add interviewer's and interviewee's title. Upload final copy to youtube. 

### Interviewee:
Karla Blaine
BSN, RN, CPHQ, IQCI
Program Manager

From SW Engr Site:

Produce a 2-minute video interview where customer describes the problem you will be solving and the application you will be building.
See an example interview.
Note 1: this example was made at the end of the project, so the questions are somewhat different from what you should ask.
Note 2: you may directly embed the video in the submitted pdf file, or upload the video to vimeo or youtube and include the link in the pdf.

**Comment by bajabob** [comment]
Video is complete @baileybauman 

https://goo.gl/XoBKBw

**Comment by baileybauman** [comment]
Thanks Bob, it looks great!
