### ISSUE TITLE
Create at least 4 user stories

### ISSUE THREAD

**Issue by bajabob** [bajabob/Patient-Itinerary-Planner#8]
User stories: Create at least 4 user stories on 3x5 cards. These should be in the format shown in Chapter 7. You can submit photos of the 3x5 cards or type them up. Example:

- Feature: Add a movie to Rotten Potatoes
   - As a movie fan
   - So that I can share a movie with other movie fans
   - I want to add a movie to the Rotten Potatoes database

**Comment by baileybauman** [comment]
finished
